var exhibitions  = {
    details:
		[
			{
				exhibitionId: '01',
				date: 'MONDAY, 10 JULY 2017',
				location: 'President of the Institute for New Economic Thinking',
				title: 'Opening. Where are we in year two of implementation of the 2030 Agenda?',
				shortDescr: '',
				descr: 'The 2030 Agenda for Sustainable Development, a plan of action for people, planet and prosperity, is presently in its early years of implementation. There are many positive signs - such as the widespread adoption into countries\' own development plans and strategies, and the setting up of coordinating structures and mechanisms for implementation. At the same time, certain other indicators - for example lowered projections for economic growth, or long running patterns of inequality among many different dimensions - can be cause for concern. The current year\'s review at the HLPF, around the theme of “Eradicating poverty and promoting prosperity in a changing world”, is a timely occasion to take stock of the overall objectives of the Agenda, and to assess current status and trends, as well as emerging issues that have the potential to significantly affect achievement over the years to come. Speakers at this session will bring their unique perspectives to bear on these issues, and indicate what they see as priorities needing urgent consideration. \nProposed Guiding Questions\n\nWhere are we in terms of achieving the overall objectives of Agenda 2030?\nWhat, in your understanding, are the most important trends that could affect our ability to achieve these inter-connected objectives?\nOpening Remarks\n\nH.E. Mr. Frederick Musiiwa Makamure Shava, Permanent Representative of Zimbabwe to the United Nations, President of Economic and Social Council\nIntroduction of Secretary-General’s SDG Progress Report\n\nMr. Wu Hongbo, Under-Secretary-General of Economic and Social Affairs, United Nations\nRemarks of the Major Groups and stakeholders\n\nMs. Vivania Ditukana Tatawaqa, Diverse Voices and Action for Equality from Fiji and representative of the Women\'s Major Group\nKeynote speakers\n\nMr. Robert Johnson, President of the Institute for New Economic Thinking\nMs. Sakiko Fukuda-Parr, Vice-Chair of the Committee for Development Policy, and Professor of International Affairs, The New School\nInteractive discussion',
			},
			{
				exhibitionId: '02',
				date: 'MONDAY, 11 JULY 2017',
				time: '',
				location: 'President of the Institute for New Economic Thinking',
				title: 'Opening. Where are we in year two of implementation of the 2030 Agenda?',
				shortDescr: 'The 2030 Agenda for Sustainable Development, a plan of action for people, planet and prosperity, is presently in its early years of implementation. There are many positive signs - such as the widespread adoption into countries\' own development plans and strategies, and the setting up of coordinating structures and mechanisms for implementation. At the same time, certain other indicators - for example lowered projections for economic growth, or long running patterns of inequality among many different dimensions - can be cause for concern. The current year\'s review at the HLPF, around the theme of “Eradicating poverty and promoting prosperity in a changing world”, is a timely occasion to take stock of the overall objectives of the Agenda, and to assess current status and trends, as well as emerging issues that have the potential to significantly affect achievement over the years to come. Speakers at this session will bring their unique perspectives to bear on these issues, and indicate what they see as priorities needing urgent consideration.',
				descr: 'The 2030 Agenda for Sustainable Development, a plan of action for people, planet and prosperity, is presently in its early years of implementation. There are many positive signs - such as the widespread adoption into countries\' own development plans and strategies, and the setting up of coordinating structures and mechanisms for implementation. At the same time, certain other indicators - for example lowered projections for economic growth, or long running patterns of inequality among many different dimensions - can be cause for concern. The current year\'s review at the HLPF, around the theme of “Eradicating poverty and promoting prosperity in a changing world”, is a timely occasion to take stock of the overall objectives of the Agenda, and to assess current status and trends, as well as emerging issues that have the potential to significantly affect achievement over the years to come. Speakers at this session will bring their unique perspectives to bear on these issues, and indicate what they see as priorities needing urgent consideration. \nProposed Guiding Questions\n\nWhere are we in terms of achieving the overall objectives of Agenda 2030?\nWhat, in your understanding, are the most important trends that could affect our ability to achieve these inter-connected objectives?\nOpening Remarks\n\nH.E. Mr. Frederick Musiiwa Makamure Shava, Permanent Representative of Zimbabwe to the United Nations, President of Economic and Social Council\nIntroduction of Secretary-General’s SDG Progress Report\n\nMr. Wu Hongbo, Under-Secretary-General of Economic and Social Affairs, United Nations\nRemarks of the Major Groups and stakeholders\n\nMs. Vivania Ditukana Tatawaqa, Diverse Voices and Action for Equality from Fiji and representative of the Women\'s Major Group\nKeynote speakers\n\nMr. Robert Johnson, President of the Institute for New Economic Thinking\nMs. Sakiko Fukuda-Parr, Vice-Chair of the Committee for Development Policy, and Professor of International Affairs, The New School\nInteractive discussion',
			},
			{
				exhibitionId: '03',
				date: 'MONDAY, 12 JULY 2017',
				time: '9:00 AM - 10:30 AM',
				location: 'President of the Institute for New Economic Thinking',
				title: 'Opening. Where are we in year two of implementation of the 2030 Agenda?',
				shortDescr: 'The 2030 Agenda for Sustainable Development, a plan of action for people, planet and prosperity, is presently in its early years of implementation. There are many positive signs - such as the widespread adoption into countries\' own development plans and strategies, and the setting up of coordinating structures and mechanisms for implementation. At the same time, certain other indicators - for example lowered projections for economic growth, or long running patterns of inequality among many different dimensions - can be cause for concern. The current year\'s review at the HLPF, around the theme of “Eradicating poverty and promoting prosperity in a changing world”, is a timely occasion to take stock of the overall objectives of the Agenda, and to assess current status and trends, as well as emerging issues that have the potential to significantly affect achievement over the years to come. Speakers at this session will bring their unique perspectives to bear on these issues, and indicate what they see as priorities needing urgent consideration.',
				descr: 'The 2030 Agenda for Sustainable Development, a plan of action for people, planet and prosperity, is presently in its early years of implementation. There are many positive signs - such as the widespread adoption into countries\' own development plans and strategies, and the setting up of coordinating structures and mechanisms for implementation. At the same time, certain other indicators - for example lowered projections for economic growth, or long running patterns of inequality among many different dimensions - can be cause for concern. The current year\'s review at the HLPF, around the theme of “Eradicating poverty and promoting prosperity in a changing world”, is a timely occasion to take stock of the overall objectives of the Agenda, and to assess current status and trends, as well as emerging issues that have the potential to significantly affect achievement over the years to come. Speakers at this session will bring their unique perspectives to bear on these issues, and indicate what they see as priorities needing urgent consideration. \nProposed Guiding Questions\n\nWhere are we in terms of achieving the overall objectives of Agenda 2030?\nWhat, in your understanding, are the most important trends that could affect our ability to achieve these inter-connected objectives?\nOpening Remarks\n\nH.E. Mr. Frederick Musiiwa Makamure Shava, Permanent Representative of Zimbabwe to the United Nations, President of Economic and Social Council\nIntroduction of Secretary-General’s SDG Progress Report\n\nMr. Wu Hongbo, Under-Secretary-General of Economic and Social Affairs, United Nations\nRemarks of the Major Groups and stakeholders\n\nMs. Vivania Ditukana Tatawaqa, Diverse Voices and Action for Equality from Fiji and representative of the Women\'s Major Group\nKeynote speakers\n\nMr. Robert Johnson, President of the Institute for New Economic Thinking\nMs. Sakiko Fukuda-Parr, Vice-Chair of the Committee for Development Policy, and Professor of International Affairs, The New School\nInteractive discussion',
			},

		]
};
